#!/usr/bin/env python3

import sys
import subprocess

import pandas as pd

def main():
    fields = [ 'major_pagefault_latency',
            'minor_pagefault_latency',
            'minor_pagefault_latency',
            'swap_cache_hits',
            'swapin_count',
            'swapin_prefetch_count']

    job = start_job(sys.argv[2:], memory=sys.argv[1])

    samples = []
    while job.poll() is None:
        samples.append(sample_debugfs(fields))

    samples = pd.DataFrame(data=samples, columns=fields)
    samples.to_csv(f'./{"-".join(sys.argv[2:])}samples.csv', index=False)


def start_job(cmdline, memory):
    cmdline = ['systemd-run', '--scope', 
            '-p', f'MemoryMax={memory}',
            '-p', f'MemorySwapMax=infinity'] + cmdline
    return subprocess.Popen(args=cmdline)


def sample_debugfs(files):
    entry = []
    for file in files:
        with open('/sys/kernel/debug/' + file) as f:
            entry.append(int(f.read()))
    return entry

if __name__ == "__main__":
    main()
